### ISSUE TITLE
[TODO] Blackify all files

### ISSUE THREAD

**Issue by SSS-Says-Snek** [SSS-Says-Snek/hisock#17]
**What is needing to be done currently?**
Currently, all files have different PEP8 conventions, because they've all been decided on my mood and how I was feeling to "obey PEP8" that day. So, with Black, the formatting would be much more regular, which is what we want. 

**Why aren't you doing it right now? >:(**
I'm pretty lazy, plus I'm studying electronics rn.

**Comment by AvaxarXapaxa** [comment]
'léctronic sné

**Comment by sheepy0125** [comment]
make the line length 89 or death

**Comment by SSS-Says-Snek** [comment]
nah man

**Comment by SSS-Says-Snek** [comment]
done
