### ISSUE TITLE
[TODO] Add dict-send support for HiSockServer

### ISSUE THREAD

**Issue by SSS-Says-Snek** [SSS-Says-Snek/hisock#21]
**What is needing to be done currently?**
Well, since I added dict-sending support for HiSockServer...

**Why aren't you doing it right now? >:(**
Duh.

**Comment by SSS-Says-Snek** [comment]
I swear I'll do it today :weary:

**Comment by SSS-Says-Snek** [comment]
and lol it's HiSockServer not HiSockClient

**Comment by SSS-Says-Snek** [comment]
Added

**Comment by sheepy0125** [comment]
thanks @SSS-Says-Snek :)
