### ISSUE TITLE
Feature Request: Make it so that Snek can only do 1 issue at a time

### ISSUE THREAD

**Issue by AvaxarXapaxa** [SSS-Says-Snek/hisock#24]
**Is your feature request related to a problem? Please describe.**
Like, he currently as the time of writing has 7 issues open. Be clear on one thing, smh

**Describe the solution you'd like**
~~That he be removed from the hisock development "team"~~

**Describe alternatives you've considered**
An alternative is for him to leave Alabama

**Why do you want to add this feature?**
shi de

**Additional context**
![image](https://user-images.githubusercontent.com/44055981/145123699-172513ee-c034-44d8-b4db-92249dd462ad.png)

**Comment by SSS-Says-Snek** [comment]
Censorship
