### ISSUE TITLE
10054 error for long-running client-server connections

### ISSUE THREAD

**Issue by SSS-Says-Snek** [SSS-Says-Snek/hisock#44]
**Describe the bug**
I honestly have no clue what it is (even when going on SO), hisock just throws that exception for long running client-server connections.

**To Reproduce**
I don't know, start a connection and then sleep for 8 hours?

**Expected behavior**
Obviously, no exception

**Comment by sheepy0125** [comment]
why assign me :(

**Comment by SSS-Says-Snek** [comment]
haha

**Comment by SSS-Says-Snek** [comment]
Ok I'm 99% sure it's my machine

**Comment by SSS-Says-Snek** [comment]
I'm closing this, stupid error
